//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotInfo
    {
        public int BotInfoId { get; set; }
        public int PlayerId { get; set; }
        public int AccurancyRate { get; set; }
        public int OpenRate { get; set; }
        public int StepGoalPercent { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
