//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampaignStage()
        {
            this.PlayerCampaignStageCategories = new HashSet<PlayerCampaignStageCategory>();
        }
    
        public int CampaignStageId { get; set; }
        public int StageLevel { get; set; }
        public int StarsRequired { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignStageCategory> PlayerCampaignStageCategories { get; set; }
    }
}
