//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampaignCategory()
        {
            this.CampaignSections = new HashSet<CampaignSection>();
            this.PlayerCampaignCategoryQueues = new HashSet<PlayerCampaignCategoryQueue>();
            this.PlayerCampaignStageCategories = new HashSet<PlayerCampaignStageCategory>();
        }
    
        public int CampaignCategoryId { get; set; }
        public string CategoryName { get; set; }
        public bool IsTutorial { get; set; }
        public Nullable<int> QueueLevel { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignSection> CampaignSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignCategoryQueue> PlayerCampaignCategoryQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignStageCategory> PlayerCampaignStageCategories { get; set; }
    }
}
