//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTutorialMessageStatus
    {
        public int PlayerTutorialMessageStatusId { get; set; }
        public int PlayerId { get; set; }
        public bool QuestionStatusOne { get; set; }
        public bool QuestionStatusTwo { get; set; }
        public bool CampaignSectionNewlyComlplete { get; set; }
        public bool CampaignStageNewlyUnlocked { get; set; }
        public bool CampaignStageBonus { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
