//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.PlayerCampaigns = new HashSet<PlayerCampaign>();
            this.PlayerQuestionResults = new HashSet<PlayerQuestionResult>();
            this.PlayerTutorialMessageStatuses = new HashSet<PlayerTutorialMessageStatus>();
            this.VGamePlayers = new HashSet<VGamePlayer>();
            this.VGamePlayerCategories = new HashSet<VGamePlayerCategory>();
            this.VGamePlayerSectionQuestions = new HashSet<VGamePlayerSectionQuestion>();
            this.BotInfoes = new HashSet<BotInfo>();
        }
    
        public int PlayerId { get; set; }
        public string UserName { get; set; }
        public string EmailAddr { get; set; }
        public string Password { get; set; }
        public bool FbLogin { get; set; }
        public int PlayerLevel { get; set; }
        public int CurrentSteps { get; set; }
        public int StepBank { get; set; }
        public System.DateTime LastStepUpdate { get; set; }
        public int Coins { get; set; }
        public int Stars { get; set; }
        public int Points { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public bool IsBot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaign> PlayerCampaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerQuestionResult> PlayerQuestionResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerTutorialMessageStatus> PlayerTutorialMessageStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGamePlayer> VGamePlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGamePlayerCategory> VGamePlayerCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGamePlayerSectionQuestion> VGamePlayerSectionQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BotInfo> BotInfoes { get; set; }
    }
}
