//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCampaignCategoryQueue
    {
        public int PlayerCampaignCategoryQueueId { get; set; }
        public int PlayerCampaignId { get; set; }
        public int CampaignCategoryId { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdateAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CampaignCategory CampaignCategory { get; set; }
        public virtual PlayerCampaign PlayerCampaign { get; set; }
    }
}
