//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCampaignSectionQuestion
    {
        public int PlayerCampaignSectionQuestionId { get; set; }
        public int PlayerCampaignId { get; set; }
        public int CampaignSectionId { get; set; }
        public int QuestionId { get; set; }
        public int SectionQuestionOrder { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CampaignSection CampaignSection { get; set; }
        public virtual PlayerCampaign PlayerCampaign { get; set; }
        public virtual Question Question { get; set; }
    }
}
