//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCampaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerCampaign()
        {
            this.PlayerCampaignCategoryQueues = new HashSet<PlayerCampaignCategoryQueue>();
            this.PlayerCampaignSectionQuestions = new HashSet<PlayerCampaignSectionQuestion>();
            this.PlayerCampaignStageCategories = new HashSet<PlayerCampaignStageCategory>();
        }
    
        public int PlayerCampaignId { get; set; }
        public int PlayerId { get; set; }
    
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignCategoryQueue> PlayerCampaignCategoryQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignSectionQuestion> PlayerCampaignSectionQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignStageCategory> PlayerCampaignStageCategories { get; set; }
    }
}
