//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.PlayerCampaignSectionQuestions = new HashSet<PlayerCampaignSectionQuestion>();
            this.PlayerQuestionResults = new HashSet<PlayerQuestionResult>();
            this.VGameCategorySectionQuestions = new HashSet<VGameCategorySectionQuestion>();
            this.VGamePlayerSectionQuestions = new HashSet<VGamePlayerSectionQuestion>();
        }
    
        public int QuestionId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CampaignSectionId { get; set; }
        public Nullable<int> CampaignSectionQuestionOrder { get; set; }
        public int QuestionLevel { get; set; }
        public int QuestionTypeId { get; set; }
        public string Text { get; set; }
        public Nullable<bool> HasImage { get; set; }
        public string ImageUrl { get; set; }
        public string AnswerCorrect { get; set; }
        public string AnswerWrong1 { get; set; }
        public string AnswerWrong2 { get; set; }
        public string AnswerWrong3 { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CampaignSection CampaignSection { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCampaignSectionQuestion> PlayerCampaignSectionQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerQuestionResult> PlayerQuestionResults { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGameCategorySectionQuestion> VGameCategorySectionQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VGamePlayerSectionQuestion> VGamePlayerSectionQuestions { get; set; }
    }
}
