//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TriviaTraverse171207Entities : DbContext
    {
        public TriviaTraverse171207Entities()
            : base("name=TriviaTraverse171207Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CampaignCategory> CampaignCategories { get; set; }
        public virtual DbSet<CampaignSection> CampaignSections { get; set; }
        public virtual DbSet<CampaignStage> CampaignStages { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<GameCategoryQuestionPlayerResult> GameCategoryQuestionPlayerResults { get; set; }
        public virtual DbSet<GameType> GameTypes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerCampaign> PlayerCampaigns { get; set; }
        public virtual DbSet<PlayerCampaignCategoryQueue> PlayerCampaignCategoryQueues { get; set; }
        public virtual DbSet<PlayerCampaignSectionQuestion> PlayerCampaignSectionQuestions { get; set; }
        public virtual DbSet<PlayerCampaignStageCategory> PlayerCampaignStageCategories { get; set; }
        public virtual DbSet<PlayerQuestionResult> PlayerQuestionResults { get; set; }
        public virtual DbSet<PlayerTutorialMessageStatus> PlayerTutorialMessageStatuses { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<VGame> VGames { get; set; }
        public virtual DbSet<VGameCategory> VGameCategories { get; set; }
        public virtual DbSet<VGameCategorySectionQuestion> VGameCategorySectionQuestions { get; set; }
        public virtual DbSet<VGameName> VGameNames { get; set; }
        public virtual DbSet<VGamePlayer> VGamePlayers { get; set; }
        public virtual DbSet<VGamePlayerCategory> VGamePlayerCategories { get; set; }
        public virtual DbSet<VGamePlayerSectionQuestion> VGamePlayerSectionQuestions { get; set; }
        public virtual DbSet<BotInfo> BotInfoes { get; set; }
    }
}
