//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGamePlayer
    {
        public int VGamePlayerId { get; set; }
        public int VGameId { get; set; }
        public int PlayerId { get; set; }
        public int GameSteps { get; set; }
        public System.DateTime LastStepUpdate { get; set; }
        public int Score { get; set; }
        public int Stage { get; set; }
        public int QuestionsAnswered { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public bool AutoRenew { get; set; }
        public int StepBank { get; set; }
        public int BotStageProgress { get; set; }
        public string BotAvailableQuestions { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual VGame VGame { get; set; }
    }
}
