//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaTraverseApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGamePlayerSectionQuestion
    {
        public int VGamePlayerSectionQuestionId { get; set; }
        public int VGameId { get; set; }
        public int PlayerId { get; set; }
        public int QuestionId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdateAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Question Question { get; set; }
        public virtual VGame VGame { get; set; }
    }
}
